import "@styles/style.css"

export const metadata = {
    title: "Nextjs Enrty Project",
    description: "Generated by create next app",
}

export default function Layout({ children }) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}